### ISSUE TITLE
Updates version 3.0 with italian translations

### ISSUE THREAD

**Issue by AlessioRocco** [futhr/spree-faq#2]
Can you cherry-pick this commit https://github.com/futhr/spree-faq/commit/499e983e9c24b8056f52ad11190a4af29191abaf in the `3-0-stable` branch?

If you prefer I can do another PR to that branch.

Let me know... and thanks for the merge :+1: .

**Comment by futhr** [comment]
Sorry, forgot that. It has been applied to `3-0-stable` now.
